# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('metodosDePago', '0001_initial'),
        ('distribuidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominios',
            fields=[
                ('id_dom', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_dom', models.CharField(max_length=25, unique=True, verbose_name='Nombre del dominio')),
                ('paginaWeb', models.BooleanField(default=False, verbose_name='Página web')),
                ('solicitud', models.BooleanField(default=False, verbose_name='cumplimiento solicitud de migrado')),
                ('repo', models.URLField(default='')),
                ('id_distri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidores.distribuidor', verbose_name='Distribuidor')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dominios',
                'verbose_name_plural': 'dominio',
                'db_table': 'Dominios',
            },
        ),
        migrations.CreateModel(
            name='tipoHosting',
            fields=[
                ('id_hosting', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreHosting', models.CharField(max_length=20, verbose_name='nombre del tipo de hosting')),
                ('desc', models.CharField(max_length=200, verbose_name='descripcion hosting')),
            ],
            options={
                'verbose_name': 'tipo de hosting',
                'verbose_name_plural': 'tipos de hosting',
                'db_table': 'tipoHosting',
            },
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('d_dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominios.dominios')),
                ('id_metodoDePago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodosDePago.metodosdepago')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'mfacturas',
                'db_table': 'Facturas',
            },
        ),
    ]
