# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_nombre', models.CharField(max_length=15, verbose_name='Nombre del empleado')),
                ('cargo', models.IntegerField(choices=[[1, 'Administrador de nivel'], [2, 'Asesor']], default=1)),
                ('nivel', models.IntegerField(choices=[[1, 1], [2, 2], [3, 3]], default=1)),
                ('correo', models.CharField(max_length=40)),
                ('contrase', models.CharField(default='hdfdkalhf165516', max_length=15, verbose_name='contraseña')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
