# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombrePais', models.CharField(max_length=20, verbose_name='Nombre del pais')),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombrePaquete', models.CharField(max_length=20, unique=True, verbose_name='Nombre del paquete')),
                ('cantDominios', models.IntegerField(verbose_name='Cantidad de dominios')),
                ('gbsEspacio', models.IntegerField(default=0, verbose_name='Gigas Espacio')),
                ('numCorreos', models.IntegerField(default=0, verbose_name='numero de correos corporativos')),
                ('cantBasesDatos', models.IntegerField(default=0, verbose_name='cantidad de bases de datos')),
                ('certificadoSSL', models.CharField(default='', max_length=200, verbose_name='certificado SSL')),
                ('costoBase', models.IntegerField(default=0, verbose_name='costo mensual por plan')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'db_table': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='planPago',
            fields=[
                ('id_planPago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('intervalos', models.CharField(max_length=20, unique=True, verbose_name='Intervalos de pago')),
                ('cantMeses', models.IntegerField(default=1, verbose_name='cantidad de meses por intervalo')),
                ('discount_pct', models.IntegerField(verbose_name='Porcentaje descuento del precio base')),
            ],
            options={
                'verbose_name': 'Plan de pago',
                'verbose_name_plural': 'planes de pago',
                'db_table': 'PlanPago',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
                ('contrase', models.CharField(max_length=15, verbose_name='contraseña')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tipo', models.IntegerField(choices=[[1, 'cliente'], [2, 'distribuidor']], default=1)),
                ('metodoPago', models.BooleanField(default=False, verbose_name='método de pago')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais', verbose_name='pais')),
                ('id_paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.paquetes')),
                ('id_planPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.planpago')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuarios',
            },
        ),
    ]
