# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('id_metodoDePago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numeroTarjeta', models.CharField(max_length=18)),
                ('fechaEx', models.CharField(max_length=5)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
                'db_table': 'MetodosDePago',
            },
        ),
    ]
