# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id_Ticket', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipoTicket', models.IntegerField(choices=[[1, 'Nivel 1'], [2, 'Nivel 2'], [3, 'Nivel 3']], default=1, verbose_name='Tipo de ticket')),
                ('titulo', models.CharField(default='Titulo ticket', max_length=40)),
                ('mensaje', models.TextField(max_length=500)),
                ('revisado', models.BooleanField(default=False)),
                ('id_empleado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'Tickets',
            },
        ),
    ]
